Description: Fix import of mock / mox
 The "from six.moves import mock" fails in Python 3.2, this patch fixes it.
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2014-11-12

--- a/oslotest/base.py
+++ b/oslotest/base.py
@@ -21,7 +21,10 @@ import tempfile
 
 import fixtures
 import six
-from six.moves import mock
+try:
+    from six.moves import mock
+except:
+    import mock
 import testtools
 
 _TRUE_VALUES = ('True', 'true', '1', 'yes')
--- a/oslotest/mockpatch.py
+++ b/oslotest/mockpatch.py
@@ -16,7 +16,10 @@
 # under the License.
 
 import fixtures
-from six.moves import mock
+try:
+    from six.moves import mock
+except:
+    import mock
 
 
 class _Base(fixtures.Fixture):
--- a/oslotest/moxstubout.py
+++ b/oslotest/moxstubout.py
@@ -16,7 +16,10 @@
 # under the License.
 
 import fixtures
-from six.moves import mox
+try:
+    from six.moves import mox
+except:
+    import mox
 
 
 class MoxStubout(fixtures.Fixture):
--- a/tests/unit/test_base.py
+++ b/tests/unit/test_base.py
@@ -19,7 +19,10 @@ import os
 import unittest
 
 import six
-from six.moves import mock
+try:
+    from six.moves import mock
+except:
+    import mock
 import testtools
 
 from oslotest import base
--- a/tests/unit/test_mockpatch.py
+++ b/tests/unit/test_mockpatch.py
@@ -13,7 +13,10 @@
 #    under the License.
 
 
-from six.moves import mock
+try:
+    from six.moves import mock
+except:
+    import mock
 
 from oslotest import base
 from oslotest import mockpatch
